# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: card_game.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'card_game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61rd_game.proto\"0\n\x06Player\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\"X\n\x06Target\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\x11\n\trelease_x\x18\x02 \x01(\x02\x12\x11\n\trelease_y\x18\x03 \x01(\x02\x12\x15\n\rrelease_range\x18\x04 \x01(\x02\"6\n\x10ReadyGameRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07game_id\x18\x02 \x01(\t\"5\n\x11ReadyGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x10StartGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x18\n\x07players\x18\x02 \x03(\x0b\x32\x07.Player\"5\n\x11StartGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"_\n\x0fPlayCardRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rd_id\x18\x03 \x01(\t\x12\x17\n\x06target\x18\x04 \x01(\x0b\x32\x07.Target\"4\n\x10PlayCardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"4\n\x0e\x45ndTurnRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\"3\n\x0f\x45ndTurnResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"4\n\x0e\x45ndGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\twinner_id\x18\x02 \x01(\t\"L\n\x0f\x45ndGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0f\x66inal_winner_id\x18\x03 \x01(\t2\x86\x02\n\x0f\x43\x61rdGameService\x12\x32\n\tReadyGame\x12\x11.ReadyGameRequest\x1a\x12.ReadyGameResponse\x12\x32\n\tStartGame\x12\x11.StartGameRequest\x1a\x12.StartGameResponse\x12/\n\x08PlayCard\x12\x10.PlayCardRequest\x1a\x11.PlayCardResponse\x12,\n\x07\x45ndTurn\x12\x0f.EndTurnRequest\x1a\x10.EndTurnResponse\x12,\n\x07\x45ndGame\x12\x0f.EndGameRequest\x1a\x10.EndGameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'card_game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYER']._serialized_start=19
  _globals['_PLAYER']._serialized_end=67
  _globals['_TARGET']._serialized_start=69
  _globals['_TARGET']._serialized_end=157
  _globals['_READYGAMEREQUEST']._serialized_start=159
  _globals['_READYGAMEREQUEST']._serialized_end=213
  _globals['_READYGAMERESPONSE']._serialized_start=215
  _globals['_READYGAMERESPONSE']._serialized_end=268
  _globals['_STARTGAMEREQUEST']._serialized_start=270
  _globals['_STARTGAMEREQUEST']._serialized_end=331
  _globals['_STARTGAMERESPONSE']._serialized_start=333
  _globals['_STARTGAMERESPONSE']._serialized_end=386
  _globals['_PLAYCARDREQUEST']._serialized_start=388
  _globals['_PLAYCARDREQUEST']._serialized_end=483
  _globals['_PLAYCARDRESPONSE']._serialized_start=485
  _globals['_PLAYCARDRESPONSE']._serialized_end=537
  _globals['_ENDTURNREQUEST']._serialized_start=539
  _globals['_ENDTURNREQUEST']._serialized_end=591
  _globals['_ENDTURNRESPONSE']._serialized_start=593
  _globals['_ENDTURNRESPONSE']._serialized_end=644
  _globals['_ENDGAMEREQUEST']._serialized_start=646
  _globals['_ENDGAMEREQUEST']._serialized_end=698
  _globals['_ENDGAMERESPONSE']._serialized_start=700
  _globals['_ENDGAMERESPONSE']._serialized_end=776
  _globals['_CARDGAMESERVICE']._serialized_start=779
  _globals['_CARDGAMESERVICE']._serialized_end=1041
# @@protoc_insertion_point(module_scope)
