# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: card_game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='card_game.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63\x61rd_game.proto\"\xa9\x01\n\x10ReadyGameRequest\x12\r\n\x05msgId\x18\x01 \x01(\x05\x12\r\n\x05mapId\x18\x02 \x01(\x05\x12\x10\n\x08playerId\x18\x03 \x01(\x05\x12&\n\x06heroes\x18\x04 \x03(\x0b\x32\x16.ReadyGameRequest.Hero\x1a=\n\x04Hero\x12\x14\n\x0cheroUniqueId\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x03(\t\x12\r\n\x05\x63\x61rds\x18\x03 \x03(\t\"T\n\x11ReadyGameResponse\x12\r\n\x05msgId\x18\x01 \x01(\x05\x12\x0e\n\x06roomId\x18\x02 \x01(\x05\x12\x10\n\x08playerId\x18\x03 \x01(\x05\x12\x0e\n\x06result\x18\x04 \x01(\x08\"\x93\x01\n\x10StartGameRequest\x12\r\n\x05msgId\x18\x01 \x01(\x05\x12\x0e\n\x06roomId\x18\x02 \x01(\x05\x12.\n\x06\x63hange\x18\x03 \x03(\x0b\x32\x1e.StartGameRequest.PlayerChange\x1a\x30\n\x0cPlayerChange\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\x0e\n\x06\x63hange\x18\x02 \x01(\t\"B\n\x11StartGameResponse\x12\r\n\x05msgId\x18\x01 \x01(\x05\x12\x0e\n\x06roomId\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\x08\"\x95\x02\n\x0fPlayCardRequest\x12\r\n\x05msgId\x18\x01 \x01(\x05\x12\x0e\n\x06roomId\x18\x02 \x01(\x05\x12\x10\n\x08playerId\x18\x03 \x01(\x05\x12\r\n\x05round\x18\x04 \x01(\x05\x12\'\n\x06\x63hange\x18\x05 \x03(\x0b\x32\x17.PlayCardRequest.Change\x1a\x35\n\x06\x43hange\x12+\n\x06\x63hange\x18\x01 \x01(\x0b\x32\x1b.PlayCardRequest.CardChange\x1a\x62\n\nCardChange\x12\x14\n\x0c\x63\x61rdUniqueId\x18\x01 \x01(\x05\x12\x18\n\x10release_position\x18\x02 \x03(\x05\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x14\n\x0cheroUniqueId\x18\x04 \x01(\x05\"A\n\x10PlayCardResponse\x12\r\n\x05msgId\x18\x01 \x01(\x05\x12\x0e\n\x06roomId\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\x08\x32\xaa\x01\n\x0f\x43\x61rdGameService\x12\x32\n\tReadyGame\x12\x11.ReadyGameRequest\x1a\x12.ReadyGameResponse\x12\x32\n\tStartGame\x12\x11.StartGameRequest\x1a\x12.StartGameResponse\x12/\n\x08PlayCard\x12\x10.PlayCardRequest\x1a\x11.PlayCardResponseb\x06proto3'
)




_READYGAMEREQUEST_HERO = _descriptor.Descriptor(
  name='Hero',
  full_name='ReadyGameRequest.Hero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='heroUniqueId', full_name='ReadyGameRequest.Hero.heroUniqueId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='ReadyGameRequest.Hero.position', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cards', full_name='ReadyGameRequest.Hero.cards', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=189,
)

_READYGAMEREQUEST = _descriptor.Descriptor(
  name='ReadyGameRequest',
  full_name='ReadyGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='ReadyGameRequest.msgId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mapId', full_name='ReadyGameRequest.mapId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playerId', full_name='ReadyGameRequest.playerId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heroes', full_name='ReadyGameRequest.heroes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_READYGAMEREQUEST_HERO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=189,
)


_READYGAMERESPONSE = _descriptor.Descriptor(
  name='ReadyGameResponse',
  full_name='ReadyGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='ReadyGameResponse.msgId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roomId', full_name='ReadyGameResponse.roomId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playerId', full_name='ReadyGameResponse.playerId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='ReadyGameResponse.result', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=275,
)


_STARTGAMEREQUEST_PLAYERCHANGE = _descriptor.Descriptor(
  name='PlayerChange',
  full_name='StartGameRequest.PlayerChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='StartGameRequest.PlayerChange.playerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='change', full_name='StartGameRequest.PlayerChange.change', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=425,
)

_STARTGAMEREQUEST = _descriptor.Descriptor(
  name='StartGameRequest',
  full_name='StartGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='StartGameRequest.msgId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roomId', full_name='StartGameRequest.roomId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='change', full_name='StartGameRequest.change', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STARTGAMEREQUEST_PLAYERCHANGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=425,
)


_STARTGAMERESPONSE = _descriptor.Descriptor(
  name='StartGameResponse',
  full_name='StartGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='StartGameResponse.msgId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roomId', full_name='StartGameResponse.roomId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='StartGameResponse.result', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=493,
)


_PLAYCARDREQUEST_CHANGE = _descriptor.Descriptor(
  name='Change',
  full_name='PlayCardRequest.Change',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='change', full_name='PlayCardRequest.Change.change', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=673,
)

_PLAYCARDREQUEST_CARDCHANGE = _descriptor.Descriptor(
  name='CardChange',
  full_name='PlayCardRequest.CardChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cardUniqueId', full_name='PlayCardRequest.CardChange.cardUniqueId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='release_position', full_name='PlayCardRequest.CardChange.release_position', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target', full_name='PlayCardRequest.CardChange.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heroUniqueId', full_name='PlayCardRequest.CardChange.heroUniqueId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=773,
)

_PLAYCARDREQUEST = _descriptor.Descriptor(
  name='PlayCardRequest',
  full_name='PlayCardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='PlayCardRequest.msgId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roomId', full_name='PlayCardRequest.roomId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playerId', full_name='PlayCardRequest.playerId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round', full_name='PlayCardRequest.round', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='change', full_name='PlayCardRequest.change', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PLAYCARDREQUEST_CHANGE, _PLAYCARDREQUEST_CARDCHANGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=773,
)


_PLAYCARDRESPONSE = _descriptor.Descriptor(
  name='PlayCardResponse',
  full_name='PlayCardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='PlayCardResponse.msgId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roomId', full_name='PlayCardResponse.roomId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='PlayCardResponse.result', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=840,
)

_READYGAMEREQUEST_HERO.containing_type = _READYGAMEREQUEST
_READYGAMEREQUEST.fields_by_name['heroes'].message_type = _READYGAMEREQUEST_HERO
_STARTGAMEREQUEST_PLAYERCHANGE.containing_type = _STARTGAMEREQUEST
_STARTGAMEREQUEST.fields_by_name['change'].message_type = _STARTGAMEREQUEST_PLAYERCHANGE
_PLAYCARDREQUEST_CHANGE.fields_by_name['change'].message_type = _PLAYCARDREQUEST_CARDCHANGE
_PLAYCARDREQUEST_CHANGE.containing_type = _PLAYCARDREQUEST
_PLAYCARDREQUEST_CARDCHANGE.containing_type = _PLAYCARDREQUEST
_PLAYCARDREQUEST.fields_by_name['change'].message_type = _PLAYCARDREQUEST_CHANGE
DESCRIPTOR.message_types_by_name['ReadyGameRequest'] = _READYGAMEREQUEST
DESCRIPTOR.message_types_by_name['ReadyGameResponse'] = _READYGAMERESPONSE
DESCRIPTOR.message_types_by_name['StartGameRequest'] = _STARTGAMEREQUEST
DESCRIPTOR.message_types_by_name['StartGameResponse'] = _STARTGAMERESPONSE
DESCRIPTOR.message_types_by_name['PlayCardRequest'] = _PLAYCARDREQUEST
DESCRIPTOR.message_types_by_name['PlayCardResponse'] = _PLAYCARDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadyGameRequest = _reflection.GeneratedProtocolMessageType('ReadyGameRequest', (_message.Message,), {

  'Hero' : _reflection.GeneratedProtocolMessageType('Hero', (_message.Message,), {
    'DESCRIPTOR' : _READYGAMEREQUEST_HERO,
    '__module__' : 'card_game_pb2'
    # @@protoc_insertion_point(class_scope:ReadyGameRequest.Hero)
    })
  ,
  'DESCRIPTOR' : _READYGAMEREQUEST,
  '__module__' : 'card_game_pb2'
  # @@protoc_insertion_point(class_scope:ReadyGameRequest)
  })
_sym_db.RegisterMessage(ReadyGameRequest)
_sym_db.RegisterMessage(ReadyGameRequest.Hero)

ReadyGameResponse = _reflection.GeneratedProtocolMessageType('ReadyGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _READYGAMERESPONSE,
  '__module__' : 'card_game_pb2'
  # @@protoc_insertion_point(class_scope:ReadyGameResponse)
  })
_sym_db.RegisterMessage(ReadyGameResponse)

StartGameRequest = _reflection.GeneratedProtocolMessageType('StartGameRequest', (_message.Message,), {

  'PlayerChange' : _reflection.GeneratedProtocolMessageType('PlayerChange', (_message.Message,), {
    'DESCRIPTOR' : _STARTGAMEREQUEST_PLAYERCHANGE,
    '__module__' : 'card_game_pb2'
    # @@protoc_insertion_point(class_scope:StartGameRequest.PlayerChange)
    })
  ,
  'DESCRIPTOR' : _STARTGAMEREQUEST,
  '__module__' : 'card_game_pb2'
  # @@protoc_insertion_point(class_scope:StartGameRequest)
  })
_sym_db.RegisterMessage(StartGameRequest)
_sym_db.RegisterMessage(StartGameRequest.PlayerChange)

StartGameResponse = _reflection.GeneratedProtocolMessageType('StartGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTGAMERESPONSE,
  '__module__' : 'card_game_pb2'
  # @@protoc_insertion_point(class_scope:StartGameResponse)
  })
_sym_db.RegisterMessage(StartGameResponse)

PlayCardRequest = _reflection.GeneratedProtocolMessageType('PlayCardRequest', (_message.Message,), {

  'Change' : _reflection.GeneratedProtocolMessageType('Change', (_message.Message,), {
    'DESCRIPTOR' : _PLAYCARDREQUEST_CHANGE,
    '__module__' : 'card_game_pb2'
    # @@protoc_insertion_point(class_scope:PlayCardRequest.Change)
    })
  ,

  'CardChange' : _reflection.GeneratedProtocolMessageType('CardChange', (_message.Message,), {
    'DESCRIPTOR' : _PLAYCARDREQUEST_CARDCHANGE,
    '__module__' : 'card_game_pb2'
    # @@protoc_insertion_point(class_scope:PlayCardRequest.CardChange)
    })
  ,
  'DESCRIPTOR' : _PLAYCARDREQUEST,
  '__module__' : 'card_game_pb2'
  # @@protoc_insertion_point(class_scope:PlayCardRequest)
  })
_sym_db.RegisterMessage(PlayCardRequest)
_sym_db.RegisterMessage(PlayCardRequest.Change)
_sym_db.RegisterMessage(PlayCardRequest.CardChange)

PlayCardResponse = _reflection.GeneratedProtocolMessageType('PlayCardResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYCARDRESPONSE,
  '__module__' : 'card_game_pb2'
  # @@protoc_insertion_point(class_scope:PlayCardResponse)
  })
_sym_db.RegisterMessage(PlayCardResponse)



_CARDGAMESERVICE = _descriptor.ServiceDescriptor(
  name='CardGameService',
  full_name='CardGameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=843,
  serialized_end=1013,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadyGame',
    full_name='CardGameService.ReadyGame',
    index=0,
    containing_service=None,
    input_type=_READYGAMEREQUEST,
    output_type=_READYGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartGame',
    full_name='CardGameService.StartGame',
    index=1,
    containing_service=None,
    input_type=_STARTGAMEREQUEST,
    output_type=_STARTGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PlayCard',
    full_name='CardGameService.PlayCard',
    index=2,
    containing_service=None,
    input_type=_PLAYCARDREQUEST,
    output_type=_PLAYCARDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARDGAMESERVICE)

DESCRIPTOR.services_by_name['CardGameService'] = _CARDGAMESERVICE

# @@protoc_insertion_point(module_scope)
