# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0blogin.proto\"\xd0\x01\n\rCSPlayerLogin\x12\x13\n\x05msgid\x18\xe9\x07 \x01(\x05H\x00\x88\x01\x01\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\ndeviceType\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65viceModel\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x65viceOSVersion\x18\x04 \x01(\t\x12\x12\n\ndeviceUUID\x18\x05 \x01(\t\x12\x12\n\nappversion\x18\x06 \x01(\t\x12\x12\n\nlocaleType\x18\x07 \x01(\t\x12\x13\n\x0bisReconnect\x18\x08 \x01(\x08\x42\x08\n\x06_msgid\"=\n\x0eSCLoginSuccess\x12\x13\n\x05msgid\x18\xea\x07 \x01(\x05H\x00\x88\x01\x01\x12\x0c\n\x04uuid\x18\x01 \x01(\x03\x42\x08\n\x06_msgid\".\n\rCSPlayerEnter\x12\x13\n\x05msgid\x18\xeb\x07 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_msgid\"/\n\x0e\x43SLoginGetName\x12\x13\n\x05msgid\x18\xec\x07 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_msgid\",\n\x0b\x43SEnterGame\x12\x13\n\x05msgid\x18\xed\x07 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_msgid\"@\n\x0bSCEnterGame\x12\x13\n\x05msgid\x18\xef\x07 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\nserverTime\x18\x01 \x01(\x03\x42\x08\n\x06_msgid\"\x9d\x01\n\x08SCPrompt\x12\x13\n\x05msgid\x18\xf0\x07 \x01(\x05H\x00\x88\x01\x01\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x31\n\x0c\x63ontextValue\x18\x02 \x03(\x0b\x32\x1b.SCPrompt.ContextValueEntry\x1a\x33\n\x11\x43ontextValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_msgid\"3\n\x12SCReconnectSuccess\x12\x13\n\x05msgid\x18\xf1\x07 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_msgid\"?\n\x10SCDuplicateLogin\x12\x13\n\x05msgid\x18\xf2\x07 \x01(\x05H\x00\x88\x01\x01\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\tB\x08\n\x06_msgid\"8\n\tSCKickOut\x12\x13\n\x05msgid\x18\xf3\x07 \x01(\x05H\x00\x88\x01\x01\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\tB\x08\n\x06_msgidb\x06proto3'
)




_CSPLAYERLOGIN = _descriptor.Descriptor(
  name='CSPlayerLogin',
  full_name='CSPlayerLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='CSPlayerLogin.msgid', index=0,
      number=1001, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='CSPlayerLogin.token', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceType', full_name='CSPlayerLogin.deviceType', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceModel', full_name='CSPlayerLogin.deviceModel', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceOSVersion', full_name='CSPlayerLogin.deviceOSVersion', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceUUID', full_name='CSPlayerLogin.deviceUUID', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appversion', full_name='CSPlayerLogin.appversion', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='localeType', full_name='CSPlayerLogin.localeType', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isReconnect', full_name='CSPlayerLogin.isReconnect', index=8,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='CSPlayerLogin._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=16,
  serialized_end=224,
)


_SCLOGINSUCCESS = _descriptor.Descriptor(
  name='SCLoginSuccess',
  full_name='SCLoginSuccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='SCLoginSuccess.msgid', index=0,
      number=1002, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='SCLoginSuccess.uuid', index=1,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='SCLoginSuccess._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=226,
  serialized_end=287,
)


_CSPLAYERENTER = _descriptor.Descriptor(
  name='CSPlayerEnter',
  full_name='CSPlayerEnter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='CSPlayerEnter.msgid', index=0,
      number=1003, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='CSPlayerEnter._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=289,
  serialized_end=335,
)


_CSLOGINGETNAME = _descriptor.Descriptor(
  name='CSLoginGetName',
  full_name='CSLoginGetName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='CSLoginGetName.msgid', index=0,
      number=1004, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='CSLoginGetName._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=337,
  serialized_end=384,
)


_CSENTERGAME = _descriptor.Descriptor(
  name='CSEnterGame',
  full_name='CSEnterGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='CSEnterGame.msgid', index=0,
      number=1005, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='CSEnterGame._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=386,
  serialized_end=430,
)


_SCENTERGAME = _descriptor.Descriptor(
  name='SCEnterGame',
  full_name='SCEnterGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='SCEnterGame.msgid', index=0,
      number=1007, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serverTime', full_name='SCEnterGame.serverTime', index=1,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='SCEnterGame._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=432,
  serialized_end=496,
)


_SCPROMPT_CONTEXTVALUEENTRY = _descriptor.Descriptor(
  name='ContextValueEntry',
  full_name='SCPrompt.ContextValueEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SCPrompt.ContextValueEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='SCPrompt.ContextValueEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=646,
)

_SCPROMPT = _descriptor.Descriptor(
  name='SCPrompt',
  full_name='SCPrompt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='SCPrompt.msgid', index=0,
      number=1008, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='SCPrompt.id', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contextValue', full_name='SCPrompt.contextValue', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SCPROMPT_CONTEXTVALUEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='SCPrompt._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=499,
  serialized_end=656,
)


_SCRECONNECTSUCCESS = _descriptor.Descriptor(
  name='SCReconnectSuccess',
  full_name='SCReconnectSuccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='SCReconnectSuccess.msgid', index=0,
      number=1009, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='SCReconnectSuccess._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=658,
  serialized_end=709,
)


_SCDUPLICATELOGIN = _descriptor.Descriptor(
  name='SCDuplicateLogin',
  full_name='SCDuplicateLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='SCDuplicateLogin.msgid', index=0,
      number=1010, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='SCDuplicateLogin.desc', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='SCDuplicateLogin._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=711,
  serialized_end=774,
)


_SCKICKOUT = _descriptor.Descriptor(
  name='SCKickOut',
  full_name='SCKickOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='SCKickOut.msgid', index=0,
      number=1011, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='SCKickOut.desc', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_msgid', full_name='SCKickOut._msgid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=776,
  serialized_end=832,
)

_CSPLAYERLOGIN.oneofs_by_name['_msgid'].fields.append(
  _CSPLAYERLOGIN.fields_by_name['msgid'])
_CSPLAYERLOGIN.fields_by_name['msgid'].containing_oneof = _CSPLAYERLOGIN.oneofs_by_name['_msgid']
_SCLOGINSUCCESS.oneofs_by_name['_msgid'].fields.append(
  _SCLOGINSUCCESS.fields_by_name['msgid'])
_SCLOGINSUCCESS.fields_by_name['msgid'].containing_oneof = _SCLOGINSUCCESS.oneofs_by_name['_msgid']
_CSPLAYERENTER.oneofs_by_name['_msgid'].fields.append(
  _CSPLAYERENTER.fields_by_name['msgid'])
_CSPLAYERENTER.fields_by_name['msgid'].containing_oneof = _CSPLAYERENTER.oneofs_by_name['_msgid']
_CSLOGINGETNAME.oneofs_by_name['_msgid'].fields.append(
  _CSLOGINGETNAME.fields_by_name['msgid'])
_CSLOGINGETNAME.fields_by_name['msgid'].containing_oneof = _CSLOGINGETNAME.oneofs_by_name['_msgid']
_CSENTERGAME.oneofs_by_name['_msgid'].fields.append(
  _CSENTERGAME.fields_by_name['msgid'])
_CSENTERGAME.fields_by_name['msgid'].containing_oneof = _CSENTERGAME.oneofs_by_name['_msgid']
_SCENTERGAME.oneofs_by_name['_msgid'].fields.append(
  _SCENTERGAME.fields_by_name['msgid'])
_SCENTERGAME.fields_by_name['msgid'].containing_oneof = _SCENTERGAME.oneofs_by_name['_msgid']
_SCPROMPT_CONTEXTVALUEENTRY.containing_type = _SCPROMPT
_SCPROMPT.fields_by_name['contextValue'].message_type = _SCPROMPT_CONTEXTVALUEENTRY
_SCPROMPT.oneofs_by_name['_msgid'].fields.append(
  _SCPROMPT.fields_by_name['msgid'])
_SCPROMPT.fields_by_name['msgid'].containing_oneof = _SCPROMPT.oneofs_by_name['_msgid']
_SCRECONNECTSUCCESS.oneofs_by_name['_msgid'].fields.append(
  _SCRECONNECTSUCCESS.fields_by_name['msgid'])
_SCRECONNECTSUCCESS.fields_by_name['msgid'].containing_oneof = _SCRECONNECTSUCCESS.oneofs_by_name['_msgid']
_SCDUPLICATELOGIN.oneofs_by_name['_msgid'].fields.append(
  _SCDUPLICATELOGIN.fields_by_name['msgid'])
_SCDUPLICATELOGIN.fields_by_name['msgid'].containing_oneof = _SCDUPLICATELOGIN.oneofs_by_name['_msgid']
_SCKICKOUT.oneofs_by_name['_msgid'].fields.append(
  _SCKICKOUT.fields_by_name['msgid'])
_SCKICKOUT.fields_by_name['msgid'].containing_oneof = _SCKICKOUT.oneofs_by_name['_msgid']
DESCRIPTOR.message_types_by_name['CSPlayerLogin'] = _CSPLAYERLOGIN
DESCRIPTOR.message_types_by_name['SCLoginSuccess'] = _SCLOGINSUCCESS
DESCRIPTOR.message_types_by_name['CSPlayerEnter'] = _CSPLAYERENTER
DESCRIPTOR.message_types_by_name['CSLoginGetName'] = _CSLOGINGETNAME
DESCRIPTOR.message_types_by_name['CSEnterGame'] = _CSENTERGAME
DESCRIPTOR.message_types_by_name['SCEnterGame'] = _SCENTERGAME
DESCRIPTOR.message_types_by_name['SCPrompt'] = _SCPROMPT
DESCRIPTOR.message_types_by_name['SCReconnectSuccess'] = _SCRECONNECTSUCCESS
DESCRIPTOR.message_types_by_name['SCDuplicateLogin'] = _SCDUPLICATELOGIN
DESCRIPTOR.message_types_by_name['SCKickOut'] = _SCKICKOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CSPlayerLogin = _reflection.GeneratedProtocolMessageType('CSPlayerLogin', (_message.Message,), {
  'DESCRIPTOR' : _CSPLAYERLOGIN,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:CSPlayerLogin)
  })
_sym_db.RegisterMessage(CSPlayerLogin)

SCLoginSuccess = _reflection.GeneratedProtocolMessageType('SCLoginSuccess', (_message.Message,), {
  'DESCRIPTOR' : _SCLOGINSUCCESS,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:SCLoginSuccess)
  })
_sym_db.RegisterMessage(SCLoginSuccess)

CSPlayerEnter = _reflection.GeneratedProtocolMessageType('CSPlayerEnter', (_message.Message,), {
  'DESCRIPTOR' : _CSPLAYERENTER,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:CSPlayerEnter)
  })
_sym_db.RegisterMessage(CSPlayerEnter)

CSLoginGetName = _reflection.GeneratedProtocolMessageType('CSLoginGetName', (_message.Message,), {
  'DESCRIPTOR' : _CSLOGINGETNAME,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:CSLoginGetName)
  })
_sym_db.RegisterMessage(CSLoginGetName)

CSEnterGame = _reflection.GeneratedProtocolMessageType('CSEnterGame', (_message.Message,), {
  'DESCRIPTOR' : _CSENTERGAME,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:CSEnterGame)
  })
_sym_db.RegisterMessage(CSEnterGame)

SCEnterGame = _reflection.GeneratedProtocolMessageType('SCEnterGame', (_message.Message,), {
  'DESCRIPTOR' : _SCENTERGAME,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:SCEnterGame)
  })
_sym_db.RegisterMessage(SCEnterGame)

SCPrompt = _reflection.GeneratedProtocolMessageType('SCPrompt', (_message.Message,), {

  'ContextValueEntry' : _reflection.GeneratedProtocolMessageType('ContextValueEntry', (_message.Message,), {
    'DESCRIPTOR' : _SCPROMPT_CONTEXTVALUEENTRY,
    '__module__' : 'login_pb2'
    # @@protoc_insertion_point(class_scope:SCPrompt.ContextValueEntry)
    })
  ,
  'DESCRIPTOR' : _SCPROMPT,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:SCPrompt)
  })
_sym_db.RegisterMessage(SCPrompt)
_sym_db.RegisterMessage(SCPrompt.ContextValueEntry)

SCReconnectSuccess = _reflection.GeneratedProtocolMessageType('SCReconnectSuccess', (_message.Message,), {
  'DESCRIPTOR' : _SCRECONNECTSUCCESS,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:SCReconnectSuccess)
  })
_sym_db.RegisterMessage(SCReconnectSuccess)

SCDuplicateLogin = _reflection.GeneratedProtocolMessageType('SCDuplicateLogin', (_message.Message,), {
  'DESCRIPTOR' : _SCDUPLICATELOGIN,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:SCDuplicateLogin)
  })
_sym_db.RegisterMessage(SCDuplicateLogin)

SCKickOut = _reflection.GeneratedProtocolMessageType('SCKickOut', (_message.Message,), {
  'DESCRIPTOR' : _SCKICKOUT,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:SCKickOut)
  })
_sym_db.RegisterMessage(SCKickOut)


_SCPROMPT_CONTEXTVALUEENTRY._options = None
# @@protoc_insertion_point(module_scope)
